# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: >
        sudo apt-get install haskell-platform cabal-install build-essential
        curl file git graphviz &&
        sudo apt-get --no-install-recommends install texlive-{base,generic-recommended,fonts-recommended,latex-base,latex-recommended,latex-extra,pictures,pstricks,science,fonts-extra} tex-gyre texlive-xetex lmodern

    - name: Install homebrew
      run: >
        git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew &&
        mkdir ~/.linuxbrew/bin &&
        ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin &&
        eval $(~/.linuxbrew/bin/brew shellenv)

    - name: Install pandoc and friends
      run: brew install pandoc-crossref pandoc pandoc-citeproc

    - name: Build the report
      run: cd $GITHUB_WORKSPACE && make
